import type { VolcanoFeature } from '@/types/volcano';

/**
 * Real-world volcano dataset for the deep‑earth simulator.
 *
 * Credit: Global Volcanism Program, Smithsonian Institution.
 * Volcanoes of the World. https://volcano.si.edu/ (educational, non-commercial use)
 *
 * All primary facts (names, coordinates, elevations and last eruption years)
 * were sourced from the Smithsonian Institution’s Global Volcanism Program
 * database as available in July 2026.  Derived parameters such as heightKm,
 * baseRadiusKm, craterRadiusKm, eruptionThreshold and activity fields are
 * computed mechanically following the rules described in the accompanying
 * research instructions (§2).  The `mantleThetaDeg` value is not a
 * geophysical measurement – it’s an educational cue used by the simulator to
 * position each volcano within a simplified mantle convection model.
 */

export const realVolcanoes: VolcanoFeature[] = [
  {
    id: 'volcano-mount-fuji',
    name: 'Mount Fuji',
    nameJa: '富士山',
    type: 'stratovolcano',
    lat: 35.36,
    lon: 138.73,
    heightKm: 3.78,
    baseRadiusKm: 22.68,
    craterRadiusKm: 1.32,
    mantleSampleDepthKm: 80,
    eruptionThreshold: 0.62,
    mantleThetaDeg: 100,
    activity: { heat: 0.30, pressure: 0.25, gas: 0.25, eruption: 0.0 },
  },
  {
    id: 'volcano-sakurajima',
    name: 'Sakurajima',
    nameJa: '桜島',
    type: 'stratovolcano',
    lat: 31.58,
    lon: 130.66,
    heightKm: 1.12,
    baseRadiusKm: 6.72,
    craterRadiusKm: 0.39,
    mantleSampleDepthKm: 80,
    eruptionThreshold: 0.45,
    mantleThetaDeg: 110,
    activity: { heat: 0.85, pressure: 0.75, gas: 0.70, eruption: 0.60 },
  },
  {
    id: 'volcano-mount-st-helens',
    name: 'Mount St. Helens',
    nameJa: 'セントヘレンズ山',
    type: 'stratovolcano',
    lat: 46.19,
    lon: -122.19,
    heightKm: 2.55,
    baseRadiusKm: 15.30,
    craterRadiusKm: 0.89,
    mantleSampleDepthKm: 80,
    eruptionThreshold: 0.55,
    mantleThetaDeg: 104,
    activity: { heat: 0.55, pressure: 0.45, gas: 0.45, eruption: 0.0 },
  },
  {
    id: 'volcano-mount-pinatubo',
    name: 'Mount Pinatubo',
    nameJa: 'ピナトゥボ山',
    type: 'stratovolcano',
    lat: 15.14,
    lon: 120.35,
    heightKm: 1.49,
    baseRadiusKm: 8.94,
    craterRadiusKm: 0.52,
    mantleSampleDepthKm: 80,
    eruptionThreshold: 0.55,
    mantleThetaDeg: 112,
    activity: { heat: 0.55, pressure: 0.45, gas: 0.45, eruption: 0.0 },
  },
  {
    id: 'volcano-mount-merapi',
    name: 'Mount Merapi',
    nameJa: 'ムラピ山',
    type: 'stratovolcano',
    lat: -7.54,
    lon: 110.45,
    heightKm: 2.97,
    baseRadiusKm: 17.82,
    craterRadiusKm: 1.04,
    mantleSampleDepthKm: 80,
    eruptionThreshold: 0.45,
    mantleThetaDeg: 108,
    activity: { heat: 0.85, pressure: 0.75, gas: 0.70, eruption: 0.60 },
  },
  {
    id: 'volcano-kilauea',
    name: 'Kīlauea',
    nameJa: 'キラウエア山',
    type: 'shield',
    lat: 19.42,
    lon: -155.29,
    heightKm: 1.25,
    baseRadiusKm: 25.00,
    craterRadiusKm: 1.25,
    mantleSampleDepthKm: 120,
    eruptionThreshold: 0.40,
    mantleThetaDeg: 54,
    activity: { heat: 0.85, pressure: 0.75, gas: 0.60, eruption: 0.60 },
  },
  {
    id: 'volcano-mauna-loa',
    name: 'Mauna Loa',
    nameJa: 'マウナロア山',
    type: 'shield',
    lat: 19.48,
    lon: -155.60,
    heightKm: 4.17,
    baseRadiusKm: 83.40,
    craterRadiusKm: 4.17,
    mantleSampleDepthKm: 120,
    eruptionThreshold: 0.50,
    mantleThetaDeg: 126,
    activity: { heat: 0.55, pressure: 0.45, gas: 0.35, eruption: 0.0 },
  },
  {
    id: 'volcano-eyjafjallajokull',
    name: 'Eyjafjallajökull',
    nameJa: 'エイヤフィヤトラヨークトル山',
    type: 'stratovolcano',
    lat: 63.62,
    lon: -19.61,
    heightKm: 1.65,
    baseRadiusKm: 9.90,
    craterRadiusKm: 0.58,
    mantleSampleDepthKm: 120,
    eruptionThreshold: 0.55,
    mantleThetaDeg: 198,
    activity: { heat: 0.55, pressure: 0.45, gas: 0.45, eruption: 0.0 },
  },
  {
    id: 'volcano-piton-de-la-fournaise',
    name: 'Piton de la Fournaise',
    nameJa: 'ピトン・ド・ラ・フルネーズ山',
    type: 'shield',
    lat: -21.24,
    lon: 55.71,
    heightKm: 2.62,
    baseRadiusKm: 52.40,
    craterRadiusKm: 2.62,
    mantleSampleDepthKm: 120,
    eruptionThreshold: 0.40,
    mantleThetaDeg: 270,
    activity: { heat: 0.85, pressure: 0.75, gas: 0.60, eruption: 0.60 },
  },
  {
    id: 'volcano-mount-etna',
    name: 'Mount Etna',
    nameJa: 'エトナ山',
    type: 'stratovolcano',
    lat: 37.76,
    lon: 14.99,
    heightKm: 3.40,
    baseRadiusKm: 20.40,
    craterRadiusKm: 1.19,
    mantleSampleDepthKm: 80,
    eruptionThreshold: 0.45,
    mantleThetaDeg: 160,
    activity: { heat: 0.85, pressure: 0.75, gas: 0.70, eruption: 0.60 },
  },
  {
    id: 'volcano-mount-vesuvius',
    name: 'Mount Vesuvius',
    nameJa: 'ヴェスヴィオ山',
    type: 'stratovolcano',
    lat: 40.82,
    lon: 14.43,
    heightKm: 1.28,
    baseRadiusKm: 7.68,
    craterRadiusKm: 0.45,
    mantleSampleDepthKm: 80,
    eruptionThreshold: 0.55,
    mantleThetaDeg: 162,
    activity: { heat: 0.55, pressure: 0.45, gas: 0.45, eruption: 0.0 },
  },
  {
    id: 'volcano-mount-nyiragongo',
    name: 'Mount Nyiragongo',
    nameJa: 'ニイラゴンゴ山',
    type: 'stratovolcano',
    lat: -1.52,
    lon: 29.25,
    heightKm: 3.47,
    baseRadiusKm: 20.82,
    craterRadiusKm: 1.21,
    mantleSampleDepthKm: 60,
    eruptionThreshold: 0.45,
    mantleThetaDeg: 60,
    activity: { heat: 0.85, pressure: 0.75, gas: 0.70, eruption: 0.60 },
  },
  {
    id: 'volcano-yellowstone-caldera',
    name: 'Yellowstone Caldera',
    nameJa: 'イエローストーン・カルデラ',
    type: 'caldera',
    lat: 44.40,
    lon: -110.70,
    heightKm: 1.50,
    baseRadiusKm: 16.00,
    craterRadiusKm: 6.40,
    mantleSampleDepthKm: 80,
    eruptionThreshold: 0.70,
    mantleThetaDeg: 18,
    activity: { heat: 0.12, pressure: 0.20, gas: 0.20, eruption: 0.0 },
  },
  {
    id: 'volcano-mount-aso',
    name: 'Mount Aso',
    nameJa: '阿蘇山',
    type: 'caldera',
    lat: 32.88,
    lon: 131.10,
    heightKm: 1.50,
    baseRadiusKm: 12.00,
    craterRadiusKm: 4.80,
    mantleSampleDepthKm: 80,
    eruptionThreshold: 0.45,
    mantleThetaDeg: 115,
    activity: { heat: 0.85, pressure: 0.85, gas: 0.80, eruption: 0.60 },
  },
  {
    id: 'volcano-santorini-caldera',
    name: 'Santorini Caldera',
    nameJa: 'サントリーニ・カルデラ',
    type: 'caldera',
    lat: 36.40,
    lon: 25.46,
    heightKm: 0.37,
    baseRadiusKm: 10.00,
    craterRadiusKm: 4.00,
    mantleSampleDepthKm: 80,
    eruptionThreshold: 0.55,
    mantleThetaDeg: 200,
    activity: { heat: 0.55, pressure: 0.55, gas: 0.55, eruption: 0.0 },
  },
  {
    id: 'volcano-paricutin',
    name: 'Parícutin',
    nameJa: 'パリクティン山',
    type: 'cinder_cone',
    lat: 19.49,
    lon: -102.25,
    heightKm: 0.60,
    baseRadiusKm: 2.40,
    craterRadiusKm: 0.30,
    mantleSampleDepthKm: 80,
    eruptionThreshold: 0.55,
    mantleThetaDeg: 210,
    activity: { heat: 0.55, pressure: 0.45, gas: 0.45, eruption: 0.0 },
  },
  {
    id: 'volcano-kama-ehuakanaloa',
    name: "Kama'ehuakanaloa",
    nameJa: 'カマエフカナロア海底火山',
    type: 'submarine',
    lat: 18.92,
    lon: -155.27,
    heightKm: 3.00,
    baseRadiusKm: 24.00,
    craterRadiusKm: 1.20,
    mantleSampleDepthKm: 120,
    eruptionThreshold: 0.55,
    mantleThetaDeg: 342,
    activity: { heat: 0.55, pressure: 0.45, gas: 0.45, eruption: 0.0 },
  },
  {
    id: 'volcano-fukutoku-okanoba',
    name: 'Fukutoku-Okanoba',
    nameJa: '福徳岡ノ場',
    type: 'submarine',
    lat: 24.28,
    lon: 141.48,
    heightKm: 0.30,
    baseRadiusKm: 2.40,
    craterRadiusKm: 0.12,
    mantleSampleDepthKm: 80,
    eruptionThreshold: 0.55,
    mantleThetaDeg: 220,
    activity: { heat: 0.55, pressure: 0.45, gas: 0.45, eruption: 0.0 },
  },
  {
    id: 'volcano-cotopaxi',
    name: 'Cotopaxi',
    nameJa: 'コトパクシ山',
    type: 'stratovolcano',
    lat: -0.68,
    lon: -78.44,
    heightKm: 5.90,
    baseRadiusKm: 35.40,
    craterRadiusKm: 2.07,
    mantleSampleDepthKm: 80,
    eruptionThreshold: 0.55,
    mantleThetaDeg: 98,
    activity: { heat: 0.55, pressure: 0.45, gas: 0.45, eruption: 0.0 },
  },
  {
    id: 'volcano-mount-teide',
    name: 'Mount Teide',
    nameJa: 'テイデ山',
    type: 'stratovolcano',
    lat: 28.27,
    lon: -16.64,
    heightKm: 3.72,
    baseRadiusKm: 22.32,
    craterRadiusKm: 1.30,
    mantleSampleDepthKm: 120,
    eruptionThreshold: 0.55,
    mantleThetaDeg: 345,
    activity: { heat: 0.55, pressure: 0.45, gas: 0.45, eruption: 0.0 },
  },
  {
    id: 'volcano-mount-kilimanjaro',
    name: 'Mount Kilimanjaro',
    nameJa: 'キリマンジャロ山',
    type: 'stratovolcano',
    lat: -3.07,
    lon: 37.35,
    heightKm: 5.90,
    baseRadiusKm: 35.40,
    craterRadiusKm: 2.07,
    mantleSampleDepthKm: 80,
    eruptionThreshold: 0.70,
    mantleThetaDeg: 234,
    activity: { heat: 0.12, pressure: 0.10, gas: 0.10, eruption: 0.0 },
  },
];